### ISSUE TITLE
Cellect server should be running on JRuby

### ISSUE THREAD

**Issue by camallen** [zooniverse/cellect_panoptes#1]
Cellect server uses Celluloid and Puma. If we run in MRI ruby the GIL will derail concurrent performance improvements.
https://github.com/zooniverse/cellect_panoptes/blob/master/Dockerfile#L1

**Comment by parrish** [comment]
Except it's using a C extension for set operations (via libboost)

Short of trying to re-implement a Java version, I don't have any suggestions for this.

**Comment by camallen** [comment]
Indeed! This looks promising though, http://www.chrisseaton.com/rubytruffle/cext/
